src/main.js

Handle missing yarn gracefully

---

bootstrap/package.json
bootstrap/yarn.lock

This sets the gooddata-react-components to latest stable release.

RELATED: RAIL-1690 prepare GA version

---

bootstrap/.gitignore
bootstrap/README.md
bootstrap/package.json
bootstrap/scripts/refresh-ldm.js
bootstrap/yarn.lock

RELATED: RAIL-2176 Integrate catalog-export tool to boilerplate

---

bootstrap/src/ldm/full.ts

BUGFIX: RAIL-2365 Fix boilerplate issue with a .ts file being empty

---

bootstrap/package.json

RELATED: RAIL-2407 Integrate catalog export with boilerplate

---

README.md
bootstrap/package.json
bootstrap/yarn.lock
index.js
sampleConfig.json
src/__tests__/configBootstrap.test.js
src/__tests__/stringUtils.test.js
src/cliBootstrap.js
src/configBootstrap.js
src/inquiries.js
src/main.js
src/stringUtils.js

Changes domain to hostname, keeps its schema.
Adds default workspace value for tiger backends.
Fixes tiger proxy setup and authentication. For now the Login button is hidden in tiger
and we rely on the basic auth dialog.
Also removes react-components as they are no longer needed.

RELATED: RAIL-2407 improve tiger backend support

---

bootstrap/src/contexts/Auth/backend--tiger.js
bootstrap/src/contexts/Auth/backend.js
bootstrap/src/contexts/Auth/context.js
src/main.js

-  'Login' is shown even if the user is already logged in (has valid cookies etc). This was problem with bear because of bad default auth provider.
-  Clean up backend setup code

RELATED: RAIL-2786 - Fix authentication glitches

---

bootstrap/src/contexts/WorkspaceList.js

-  Workspace retrieval was messed up and resulted in repeated requests
-  The transformation code did not reflect changes to backend-spi that we did
for 8.0 GA. WS query returns IAnalyticalWorkspace and not workspace descriptor.
Code would bomb on this while trying to access invalid properties
JIRA: RAIL-2786

RELATED: RAIL-2786 - Fix workspace list provider

---

bootstrap/HOTWO.md
bootstrap/README--tiger.md
bootstrap/README.md
bootstrap/src/contexts/Auth/backend--tiger.js

-  README improvements
-  Support for Tiger authentication in prod & development mods
-  Enhanced Tiger documentation

RELATED: RAIL-2924 - Tiger auth

---

bootstrap/src/routes/Welcome--tiger.tsx
bootstrap/src/routes/Welcome.tsx

RELATED: RAIL-3078 Link to the new Examples Gallery

---

bootstrap/package.json
src/performTemplateReplacements.js

-  Tiger AIO is by default using 3000
-  Tiger AIO is set up with CORS on port 8443
JIRA: RAIL-3051

RELATED: RAIL-3051 - Change default app port when using tiger backend

---

bootstrap/src/contexts/Auth/backend--tiger.ts

Add timeout before app redirect to login flow

---

bootstrap/HOWTO.md
bootstrap/README--tiger.md
bootstrap/README.md
bootstrap/src/routes/Welcome--tiger.tsx
src/main.js
src/pathUtils.js
src/processTigerFiles.js
src/removeBackendInvalidFiles.js

We do not have a good enough docker configuration for tiger at the moment, so we remove the mentions of it altogether in tiger.

RELATED: RAIL-3191 remove docker stuff in tiger builds

---

bootstrap/src/routes/Welcome--tiger.tsx

RELATED: RAIL-3191 Use GoodData.CN instead of Anywhere

---

bootstrap/README--tiger.md

RELATED: RAIL-3191 Explain GoodData.CN is tiger and use it

---

bootstrap/README--tiger.md
bootstrap/README.md
bootstrap/package.json
bootstrap/scripts/refresh-md.js
bootstrap/src/constants.ts
bootstrap/src/ldm/full.ts
bootstrap/src/md/full.ts
bootstrap/src/routes/Welcome--tiger.tsx
bootstrap/src/routes/Welcome.tsx
src/performTemplateReplacements.js

- LDM renamed to MD
- refresh-ldm script renamed to refresh-md
- ldm directory renamed to md directory
JIRA: RAIL-3250

Renaming LDM to MD

---

bootstrap/docker/nginx.conf.template

-  this error: https://stackoverflow.com/questions/46467613/nginx-upstream-ssl-peer-closed-connection-in-ssl-handshake
JIRA: RAIL-2092

RELATED: RAIL-2092 - Enhance proxy setup to prevent errors on some machines

---

bootstrap/README--tiger.md
bootstrap/README.md

RELATED: RAIL-3517 Fix outdated and broken links

---

src/inquiries.js

- block user to use http protocol while creating gooddata-react-app on bear backend
JIRA: RAIL-3552

RAIL-3552 Custom domain validation

---

index.js
src/cliBootstrap.js
src/inquiries.js

- add platform (Tiger/Bear) inquiry
- make typescript a preferred option
JIRA: RAIL-3588

RAIL-3588 platform picker

---

bootstrap/README--tiger.md
bootstrap/src/setupProxy.js

* Fix the proxy according to the new needs of the Tiger setup.
* Fix the regex for the protocol to only mathc the start of the string.
* Unify naming of the REACT_APP_DEV_TIGER_API_TOKEN variable in README.
JIRA: RAIL-4012

RELATED: RAIL-4012 Fix proxy issues on tiger, fix tiger readme

---

package.json

-add minimal node version to root package.json
JIRA: RAIL-3558

Define minimal node version in root app

---

bootstrap/src/routes/Welcome--tiger.tsx
bootstrap/src/routes/Welcome.tsx

- Wrap InsightView in container with set size (otherwise, rendered insight is hidden)
JIRA: RAIL-4245

Correct example on welcome page

---

scripts/build.sh

- replace with cp and rm commands
JIRA: RAIL-4047

Remove rsync from build step

---

scripts/build.sh

Bugfix: CP is working differently on linux than on masOS

---

README.md

- because --ignore-existing parameter was removed from npx
JIRA: RAIL-4358

Remove obsolette param from the readme

---

bootstrap/package.json
bootstrap/yarn.lock

BUGFIX: 'InsightView' cannot be used as a JSX component

---

scripts/build.sh

RELATED: RAIL-4372 Fix removal of TypeScript files

---

bootstrap/package.json
bootstrap/yarn.lock
src/performTemplateReplacements.js

This makes sure that the tiger version is consistent with the rest of
the SDK packages.
JIRA: RAIL-4371

RELATED: RAIL-4371 Include tiger backend in the lockfile

---

.fossa.yml
gdc_fossa.yaml

+ cherry-pick 1 commit from master

DC-2429: Use fossa v3 instead

---

README.md

- Force npx to install the latest stable version
JIRA: RAIL-4584

Correct npx commands in readme

---

yarn.lock

RELATED: FET-1201 update pkg

---

yarn.lock

build: fix vulnerabilities

---

bootstrap/README.md

Mark package as deprecated.
Mention `@gooddata/app-toolkit` as a possible replacement.
JIRA: RAIL-5040

chore: mark as deprecated
